name: CI Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository's code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use Python 3.8 (you can adjust the version as needed)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run unit tests with unittest
        run: |
          python -m unittest discover -s tests  # Discover and run unittests in the tests directory

      - name: Run tests with pytest
        run: |
          pip install pytest  # Install pytest
          pytest --maxfail=1 --disable-warnings -q  # Run tests with pytest (fail after 1 failure, no warnings, quiet output)

    # Fail the workflow if any tests fail
    if: failure()
    continue-on-error: false  # This will ensure the job fails on any test failure

