name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Code (Optional)
        run: |
          pip install flake8
          flake8 app --ignore=E501  # Ignore long line warnings

      - name: Run Unit Tests (unittest)
        run: |
          export PYTHONWARNINGS="ignore"
          python -m unittest discover tests

      - name: Ensure Application Builds
        run: python run.py  # Ensure the Flask app starts up without errors
